# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Boggle_Game.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Room_Game(object):
    def setupUi(self, Room_Game):
        Room_Game.setObjectName("Room_Game")
        Room_Game.resize(522, 388)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Room_Game)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_horizontalLayout = QtWidgets.QHBoxLayout()
        self.time_horizontalLayout.setObjectName("time_horizontalLayout")
        self.remainingTime = QtWidgets.QLabel(Room_Game)
        self.remainingTime.setObjectName("remainingTime")
        self.time_horizontalLayout.addWidget(self.remainingTime)
        self.progressBar = QtWidgets.QProgressBar(Room_Game)
        self.progressBar.setMaximum(180)
        self.progressBar.setProperty("value", 34)
        self.progressBar.setObjectName("progressBar")
        self.time_horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.time_horizontalLayout)
        self.words_horizontalLayout = QtWidgets.QHBoxLayout()
        self.words_horizontalLayout.setObjectName("words_horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.word_0 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_0.sizePolicy().hasHeightForWidth())
        self.word_0.setSizePolicy(sizePolicy)
        self.word_0.setObjectName("word_0")
        self.gridLayout.addWidget(self.word_0, 0, 0, 1, 1)
        self.word_11 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_11.sizePolicy().hasHeightForWidth())
        self.word_11.setSizePolicy(sizePolicy)
        self.word_11.setObjectName("word_11")
        self.gridLayout.addWidget(self.word_11, 1, 3, 1, 1)
        self.word_8 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_8.sizePolicy().hasHeightForWidth())
        self.word_8.setSizePolicy(sizePolicy)
        self.word_8.setObjectName("word_8")
        self.gridLayout.addWidget(self.word_8, 0, 2, 1, 1)
        self.word_15 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_15.sizePolicy().hasHeightForWidth())
        self.word_15.setSizePolicy(sizePolicy)
        self.word_15.setObjectName("word_15")
        self.gridLayout.addWidget(self.word_15, 3, 3, 1, 1)
        self.word_7 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_7.sizePolicy().hasHeightForWidth())
        self.word_7.setSizePolicy(sizePolicy)
        self.word_7.setObjectName("word_7")
        self.gridLayout.addWidget(self.word_7, 3, 1, 1, 1)
        self.word_13 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_13.sizePolicy().hasHeightForWidth())
        self.word_13.setSizePolicy(sizePolicy)
        self.word_13.setObjectName("word_13")
        self.gridLayout.addWidget(self.word_13, 2, 3, 1, 1)
        self.word_4 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_4.sizePolicy().hasHeightForWidth())
        self.word_4.setSizePolicy(sizePolicy)
        self.word_4.setObjectName("word_4")
        self.gridLayout.addWidget(self.word_4, 2, 0, 1, 1)
        self.word_2 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_2.sizePolicy().hasHeightForWidth())
        self.word_2.setSizePolicy(sizePolicy)
        self.word_2.setObjectName("word_2")
        self.gridLayout.addWidget(self.word_2, 1, 0, 1, 1)
        self.word_5 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_5.sizePolicy().hasHeightForWidth())
        self.word_5.setSizePolicy(sizePolicy)
        self.word_5.setObjectName("word_5")
        self.gridLayout.addWidget(self.word_5, 2, 1, 1, 1)
        self.word_14 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_14.sizePolicy().hasHeightForWidth())
        self.word_14.setSizePolicy(sizePolicy)
        self.word_14.setObjectName("word_14")
        self.gridLayout.addWidget(self.word_14, 3, 2, 1, 1)
        self.word_9 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_9.sizePolicy().hasHeightForWidth())
        self.word_9.setSizePolicy(sizePolicy)
        self.word_9.setObjectName("word_9")
        self.gridLayout.addWidget(self.word_9, 0, 3, 1, 1)
        self.word_3 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_3.sizePolicy().hasHeightForWidth())
        self.word_3.setSizePolicy(sizePolicy)
        self.word_3.setObjectName("word_3")
        self.gridLayout.addWidget(self.word_3, 1, 1, 1, 1)
        self.word_12 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_12.sizePolicy().hasHeightForWidth())
        self.word_12.setSizePolicy(sizePolicy)
        self.word_12.setObjectName("word_12")
        self.gridLayout.addWidget(self.word_12, 2, 2, 1, 1)
        self.word_6 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_6.sizePolicy().hasHeightForWidth())
        self.word_6.setSizePolicy(sizePolicy)
        self.word_6.setObjectName("word_6")
        self.gridLayout.addWidget(self.word_6, 3, 0, 1, 1)
        self.word_10 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_10.sizePolicy().hasHeightForWidth())
        self.word_10.setSizePolicy(sizePolicy)
        self.word_10.setObjectName("word_10")
        self.gridLayout.addWidget(self.word_10, 1, 2, 1, 1)
        self.word_1 = QtWidgets.QPushButton(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_1.sizePolicy().hasHeightForWidth())
        self.word_1.setSizePolicy(sizePolicy)
        self.word_1.setObjectName("word_1")
        self.gridLayout.addWidget(self.word_1, 0, 1, 1, 1)
        self.words_horizontalLayout.addLayout(self.gridLayout)
        self.scrollArea = QtWidgets.QScrollArea(Room_Game)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 132, 268))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.foundedWords_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.foundedWords_label.setObjectName("foundedWords_label")
        self.verticalLayout_2.addWidget(self.foundedWords_label)
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.words_horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.words_horizontalLayout)
        self.userInput_horizontalLayout = QtWidgets.QHBoxLayout()
        self.userInput_horizontalLayout.setObjectName("userInput_horizontalLayout")
        self.guessWrod_label = QtWidgets.QLabel(Room_Game)
        self.guessWrod_label.setObjectName("guessWrod_label")
        self.userInput_horizontalLayout.addWidget(self.guessWrod_label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Room_Game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.userInput_horizontalLayout.addWidget(self.plainTextEdit)
        self.pushButton = QtWidgets.QPushButton(Room_Game)
        self.pushButton.setObjectName("pushButton")
        self.userInput_horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.userInput_horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.statusbar = QtWidgets.QStatusBar(Room_Game)
        self.statusbar.setObjectName("statusbar")
        self.verticalLayout_3.addWidget(self.statusbar)

        self.retranslateUi(Room_Game)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Room_Game)

    def retranslateUi(self, Room_Game):
        _translate = QtCore.QCoreApplication.translate
        Room_Game.setWindowTitle(_translate("Room_Game", "Room_Game"))
        self.remainingTime.setText(_translate("Room_Game", "Remaining Time:"))
        self.progressBar.setFormat(_translate("Room_Game", "%.0f seconds" % (34)))
        self.word_0.setText(_translate("Room_Game", "A"))
        self.word_11.setText(_translate("Room_Game", "Z"))
        self.word_8.setText(_translate("Room_Game", "U"))
        self.word_15.setText(_translate("Room_Game", "G"))
        self.word_7.setText(_translate("Room_Game", "H"))
        self.word_13.setText(_translate("Room_Game", "L"))
        self.word_4.setText(_translate("Room_Game", "R"))
        self.word_2.setText(_translate("Room_Game", "T"))
        self.word_5.setText(_translate("Room_Game", "P"))
        self.word_14.setText(_translate("Room_Game", "F"))
        self.word_9.setText(_translate("Room_Game", "I"))
        self.word_3.setText(_translate("Room_Game", "E"))
        self.word_12.setText(_translate("Room_Game", "K"))
        self.word_6.setText(_translate("Room_Game", "M"))
        self.word_10.setText(_translate("Room_Game", "D"))
        self.word_1.setText(_translate("Room_Game", "V"))
        self.foundedWords_label.setText(_translate("Room_Game", "Founded Words"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Room_Game", "Batata"))
        item = self.listWidget.item(1)
        item.setText(_translate("Room_Game", "Beterraba"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.guessWrod_label.setText(_translate("Room_Game", "Guess Word:"))
        self.pushButton.setText(_translate("Room_Game", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Room_Game = QtWidgets.QDialog()
    ui = Ui_Room_Game()
    ui.setupUi(Room_Game)
    Room_Game.show()
    sys.exit(app.exec_())

